import type { GraphOverview } from "./client";

export const DEMO_OVERVIEW: GraphOverview = {
  layers: {
    evidence: {
      nodes: [
        // ── Drug Discovery ─────────────────────────────────────────────────────
        { id: "ev-kras-structure-2019", label: "KRAS G12C covalent targeting (AMG510)", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "document", content_ref: "doi:10.1038/s41586-019-1694-1", tags: ["kras","sotorasib","structure"] } },
        { id: "ev-codebreak100-trial", label: "CodeBreaK 100 Phase II — Sotorasib NSCLC", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "document", content_ref: "doi:10.1056/NEJMoa2103695", tags: ["clinical-trial","sotorasib","NSCLC"] } },
        { id: "ev-bbb-assay-results", label: "BBB permeability assay — AMG510 analogues", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "sensor_window", uncertainty: 0.60, tags: ["bbb","permeability","assay"] } },
        { id: "ev-kras-pathway-review", label: "RAS–MAPK pathway review (Cell 2020)", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "document", uncertainty: 0.09, tags: ["RAS","MAPK","pathway"] } },
        { id: "ev-adagrasib-phase1", label: "Adagrasib Phase I — KRYSTAL-1 cohort", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "document", uncertainty: 0.25, tags: ["adagrasib","kras","phase1"] } },
        // ── Fukushima Governance ───────────────────────────────────────────────
        { id: "ev-tepco-2008-assessment", label: "TEPCO internal tsunami risk assessment 2008", layer: "evidence", type: "evidence",
          data: { domain: "fukushima_governance", source_type: "document", uncertainty: 0.38, tags: ["tsunami","tepco","2008","risk"] } },
        { id: "ev-jogan-geological-record", label: "Jogan earthquake 869 AD geological deposit", layer: "evidence", type: "evidence",
          data: { domain: "fukushima_governance", source_type: "document", uncertainty: 0.19, tags: ["jogan","tsunami","geology","869AD"] } },
        { id: "ev-hirai-onagawa-design", label: "Onagawa 14.8m seawall design brief (Hirai 1966)", layer: "evidence", type: "evidence",
          data: { domain: "fukushima_governance", source_type: "document", uncertainty: 0.12, tags: ["onagawa","hirai","seawall","tacit"] } },
        { id: "ev-nisa-inspection-2010", label: "NISA regulatory inspection Fukushima 2010", layer: "evidence", type: "evidence",
          data: { domain: "fukushima_governance", source_type: "document", uncertainty: 0.28, tags: ["NISA","inspection","regulation"] } },
        // ── EUV Lithography ────────────────────────────────────────────────────
        { id: "ev-prepulse-asml-2003", label: "ASML pre-pulse technique — tin droplet flatten", layer: "evidence", type: "evidence",
          data: { domain: "euv_lithography", source_type: "document", uncertainty: 0.14, tags: ["prepulse","euv","asml","droplet"] } },
        { id: "ev-mirror-contamination-field", label: "Collector mirror contamination field data", layer: "evidence", type: "evidence",
          data: { domain: "euv_lithography", source_type: "sensor_window", uncertainty: 0.22, tags: ["mirror","contamination","euv","sn"] } },
        { id: "ev-asml-throughput-2022", label: "ASML EXE:5000 >170 wafers/hour field data", layer: "evidence", type: "evidence",
          data: { domain: "euv_lithography", source_type: "sensor_window", uncertainty: 0.08, tags: ["throughput","asml","EXE5000"] } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "ev-737max-fmea-boeing", label: "Boeing 737 MAX FMEA — MCAS hazard analysis", layer: "evidence", type: "evidence",
          data: { domain: "aviation_safety", source_type: "document", uncertainty: 0.71, tags: ["737max","fmea","mcas","boeing"] } },
        { id: "ev-pierson-letter-2019", label: "Ed Pierson safety concerns letter (June 2019)", layer: "evidence", type: "evidence",
          data: { domain: "aviation_safety", source_type: "document", uncertainty: 0.10, tags: ["pierson","737max","safety","letter"] } },
        { id: "ev-jt610-accident-report", label: "KNKT Lion Air JT610 final accident report", layer: "evidence", type: "evidence",
          data: { domain: "aviation_safety", source_type: "document", uncertainty: 0.06, tags: ["jt610","lionair","accident","mcas"] } },
        { id: "ev-faa-certification-gaps", label: "FAA ODA delegation — MCAS certification review", layer: "evidence", type: "evidence",
          data: { domain: "aviation_safety", source_type: "document", uncertainty: 0.34, tags: ["faa","oda","certification","mcas"] } },
        { id: "ev-challenger-oring-tests", label: "Thiokol O-ring low-temperature test results", layer: "evidence", type: "evidence",
          data: { domain: "aviation_safety", source_type: "document", uncertainty: 0.18, tags: ["challenger","o-ring","STS-51L","temperature"] } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "ev-ipcc-ar6-spm", label: "IPCC AR6 WG1 Summary for Policymakers (2021)", layer: "evidence", type: "evidence",
          data: { domain: "climate_policy", source_type: "document", uncertainty: 0.12, tags: ["ipcc","ar6","warming","attribution"] } },
        { id: "ev-hansen-1988-testimony", label: "Hansen Senate testimony — 99% confidence (1988)", layer: "evidence", type: "evidence",
          data: { domain: "climate_policy", source_type: "document", uncertainty: 0.25, tags: ["hansen","1988","senate","CO2"] } },
        { id: "ev-glasgow-ndc-gap-2021", label: "UNEP Emissions Gap Report 2021 — 2.4°C NDC path", layer: "evidence", type: "evidence",
          data: { domain: "climate_policy", source_type: "document", uncertainty: 0.21, tags: ["glasgow","NDC","gap","emissions"] } },
        { id: "ev-arctic-sea-ice-decline", label: "Arctic sea ice extent satellite record 1979–2022", layer: "evidence", type: "evidence",
          data: { domain: "climate_policy", source_type: "sensor_window", uncertainty: 0.05, tags: ["arctic","sea-ice","satellite","trend"] } },
        // ── Surgical Robotics ──────────────────────────────────────────────────
        { id: "ev-davinci-haptic-study", label: "da Vinci haptic feedback absence — force error study", layer: "evidence", type: "evidence",
          data: { domain: "surgical_robotics", source_type: "document", uncertainty: 0.41, tags: ["davinci","haptic","force","feedback"] } },
        { id: "ev-robotic-complication-rates", label: "Robotic vs. laparoscopic complication RCT meta-analysis", layer: "evidence", type: "evidence",
          data: { domain: "surgical_robotics", source_type: "document", uncertainty: 0.29, tags: ["robotic","complication","RCT","meta"] } },
        // ── Pandemic Governance ────────────────────────────────────────────────
        { id: "ev-who-pheic-delay-2020", label: "WHO PHEIC declaration timeline — Jan 2020 gap", layer: "evidence", type: "evidence",
          data: { domain: "pandemic_governance", source_type: "document", uncertainty: 0.22, tags: ["WHO","PHEIC","delay","COVID19"] } },
        { id: "ev-aerosol-zhang-2020", label: "Zhang et al. — airborne COVID-19 transmission evidence", layer: "evidence", type: "evidence",
          data: { domain: "pandemic_governance", source_type: "document", uncertainty: 0.31, tags: ["aerosol","COVID19","airborne","zhang"] } },
        { id: "ev-china-who-reporting-gap", label: "14-day WHO reporting delay — China Jan 2020", layer: "evidence", type: "evidence",
          data: { domain: "pandemic_governance", source_type: "document", uncertainty: 0.45, tags: ["china","WHO","reporting","delay"] } },
        // ── Drug discovery additional ──────────────────────────────────────────
        { id: "ev-tp53-apoptosis-review", label: "p53 tumor suppressor apoptotic pathway (review)", layer: "evidence", type: "evidence",
          data: { domain: "drug_discovery", source_type: "document", uncertainty: 0.11, tags: ["p53","apoptosis","tumor","suppressor"] } },
        // ── Extreme Environments (source_grounded) ─────────────────────────────
        { id: "ev-boisjoly-oring-memo-1985", label: "Boisjoly O-ring erosion memo — July 31, 1985", layer: "evidence", type: "evidence",
          data: { domain: "extreme_environments", source_type: "document", uncertainty: 0.05, tags: ["challenger","o-ring","boisjoly","STS-51L","memo"] } },
        { id: "ev-challenger-temp-jan1986", label: "Challenger launch temperature 28°F — Rogers Commission", layer: "evidence", type: "evidence",
          data: { domain: "extreme_environments", source_type: "document", uncertainty: 0.04, tags: ["challenger","temperature","launch","rogers-commission"] } },
        { id: "ev-vaughan-deviance-1996", label: "Vaughan 'The Challenger Launch Decision' — normalization of deviance", layer: "evidence", type: "evidence",
          data: { domain: "extreme_environments", source_type: "document", uncertainty: 0.08, tags: ["vaughan","deviance","normalization","sociological"] } },
        { id: "ev-columbia-sts107-report-2003", label: "CAIB STS-107 Columbia foam strike analysis (2003)", layer: "evidence", type: "evidence",
          data: { domain: "extreme_environments", source_type: "document", uncertainty: 0.07, tags: ["columbia","foam","caib","STS-107"] } },
        // ── Semiconductor Hardware (hybrid) ────────────────────────────────────
        { id: "ev-tsmc-n3-process-2022", label: "TSMC N3 3nm process node production yield data", layer: "evidence", type: "evidence",
          data: { domain: "semiconductor_hardware", source_type: "document", uncertainty: 0.35, tags: ["tsmc","N3","3nm","yield","process"] } },
        { id: "ev-plasma-etch-window", label: "Plasma etch process window — HAR contact etch", layer: "evidence", type: "evidence",
          data: { domain: "semiconductor_hardware", source_type: "sensor_window", uncertainty: 0.21, tags: ["plasma","etch","process-window","HAR"] } },
        { id: "ev-spc-semiconductor-mfg", label: "SPC control chart implementation — fab line", layer: "evidence", type: "evidence",
          data: { domain: "semiconductor_hardware", source_type: "document", uncertainty: 0.18, tags: ["SPC","control-chart","fab","quality"] } },
        { id: "ev-eda-tool-dependence", label: "EDA tool vendor concentration risk (Synopsys/Cadence duopoly)", layer: "evidence", type: "evidence",
          data: { domain: "semiconductor_hardware", source_type: "document", uncertainty: 0.28, tags: ["EDA","synopsys","cadence","concentration"] } },
        // ── Mathematics Category Theory (source_grounded) ──────────────────────
        { id: "ev-eilenberg-maclane-1945", label: "Eilenberg & MacLane — 'General Theory of Natural Equivalences' (1945)", layer: "evidence", type: "evidence",
          data: { domain: "mathematics_category_theory", source_type: "document", uncertainty: 0.02, tags: ["eilenberg","maclane","category","natural-equivalences","1945"] } },
        { id: "ev-maclane-cwm-1971", label: "MacLane 'Categories for the Working Mathematician' (1971)", layer: "evidence", type: "evidence",
          data: { domain: "mathematics_category_theory", source_type: "document", uncertainty: 0.02, tags: ["maclane","CWM","textbook","functors","1971"] } },
        { id: "ev-spivak-ologs-2012", label: "Spivak ologs — category theory for knowledge representation (2012)", layer: "evidence", type: "evidence",
          data: { domain: "mathematics_category_theory", source_type: "document", uncertainty: 0.14, tags: ["spivak","olog","knowledge","applied-category-theory"] } },
        { id: "ev-awodey-ct-textbook", label: "Awodey 'Category Theory' — functor and adjunction fundamentals", layer: "evidence", type: "evidence",
          data: { domain: "mathematics_category_theory", source_type: "document", uncertainty: 0.03, tags: ["awodey","category-theory","functor","adjunction"] } },
        // ── Causality and Complex Systems (source_grounded) ────────────────────
        { id: "ev-pearl-causality-2000", label: "Pearl 'Causality' — DAGs and structural causal models (2000)", layer: "evidence", type: "evidence",
          data: { domain: "causality_and_complex_systems", source_type: "document", uncertainty: 0.04, tags: ["pearl","DAG","structural-causal-model","causality","2000"] } },
        { id: "ev-pearl-book-of-why-2018", label: "Pearl & Mackenzie 'The Book of Why' — causal hierarchy (2018)", layer: "evidence", type: "evidence",
          data: { domain: "causality_and_complex_systems", source_type: "document", uncertainty: 0.06, tags: ["pearl","causal-hierarchy","why","intervention","counterfactual"] } },
        { id: "ev-holland-rubin-causal-1986", label: "Holland 'Statistics and Causal Inference' — Rubin potential outcomes (1986)", layer: "evidence", type: "evidence",
          data: { domain: "causality_and_complex_systems", source_type: "document", uncertainty: 0.05, tags: ["holland","rubin","potential-outcomes","causal","1986"] } },
        { id: "ev-schölkopf-causal-ml-2021", label: "Schölkopf et al. — 'Toward Causal Representation Learning' (2021)", layer: "evidence", type: "evidence",
          data: { domain: "causality_and_complex_systems", source_type: "document", uncertainty: 0.22, tags: ["scholkopf","causal-representation","IRM","invariant"] } },
        // ── Information Theory (source_grounded) ───────────────────────────────
        { id: "ev-shannon-1948", label: "Shannon — 'A Mathematical Theory of Communication' (1948)", layer: "evidence", type: "evidence",
          data: { domain: "information_theory", source_type: "document", uncertainty: 0.01, tags: ["shannon","entropy","1948","channel-capacity","information"] } },
        { id: "ev-nyquist-1928", label: "Nyquist — 'Certain Topics in Telegraph Transmission' (1928)", layer: "evidence", type: "evidence",
          data: { domain: "information_theory", source_type: "document", uncertainty: 0.01, tags: ["nyquist","sampling","theorem","telegraph","1928"] } },
        { id: "ev-landauer-principle-1961", label: "Landauer — information erasure and thermodynamics (1961)", layer: "evidence", type: "evidence",
          data: { domain: "information_theory", source_type: "document", uncertainty: 0.09, tags: ["landauer","erasure","thermodynamics","kT","1961"] } },
        { id: "ev-cover-thomas-it-textbook", label: "Cover & Thomas 'Elements of Information Theory' — rate-distortion", layer: "evidence", type: "evidence",
          data: { domain: "information_theory", source_type: "document", uncertainty: 0.03, tags: ["cover","thomas","rate-distortion","channel-coding"] } },
        // ── Graph Theory and Networks (source_grounded) ────────────────────────
        { id: "ev-erdos-renyi-1959", label: "Erdős & Rényi — 'On Random Graphs' (1959)", layer: "evidence", type: "evidence",
          data: { domain: "graph_theory_and_networks", source_type: "document", uncertainty: 0.02, tags: ["erdos","renyi","random-graph","1959"] } },
        { id: "ev-barabasi-albert-1999", label: "Barabási & Albert — scale-free network power law (1999)", layer: "evidence", type: "evidence",
          data: { domain: "graph_theory_and_networks", source_type: "document", uncertainty: 0.08, tags: ["barabasi","albert","scale-free","preferential-attachment","1999"] } },
        { id: "ev-watts-strogatz-1998", label: "Watts & Strogatz — small-world network model (1998)", layer: "evidence", type: "evidence",
          data: { domain: "graph_theory_and_networks", source_type: "document", uncertainty: 0.05, tags: ["watts","strogatz","small-world","clustering","1998"] } },
        { id: "ev-spectral-graph-chung", label: "Chung 'Spectral Graph Theory' — eigenvalue-adjacency duality", layer: "evidence", type: "evidence",
          data: { domain: "graph_theory_and_networks", source_type: "document", uncertainty: 0.03, tags: ["chung","spectral","eigenvalue","adjacency","community"] } },
        // ── Translational Biomedicine (hybrid) ────────────────────────────────
        { id: "ev-ben-david-cell-lines-2019", label: "Ben-David et al. — cancer cell line genetic drift (2019)", layer: "evidence", type: "evidence",
          data: { domain: "translational_biomedicine", source_type: "document", uncertainty: 0.29, tags: ["cell-line","genetic-drift","reproducibility","culture"] } },
        { id: "ev-iom-clinical-translation-2012", label: "IOM 'Accelerating Progress in Obesity Prevention' — translation gap", layer: "evidence", type: "evidence",
          data: { domain: "translational_biomedicine", source_type: "document", uncertainty: 0.31, tags: ["IOM","translation-gap","bench-to-bedside","clinical"] } },
        { id: "ev-bbb-passive-permeability", label: "Lipinski's Rule of 5 — BBB passive diffusion constraints", layer: "evidence", type: "evidence",
          data: { domain: "translational_biomedicine", source_type: "document", uncertainty: 0.19, tags: ["lipinski","rule-of-5","BBB","permeability","MW"] } },
        // ── Developmental Biology / Morphogenesis (hybrid) ────────────────────
        { id: "ev-turing-morphogenesis-1952", label: "Turing — 'Chemical Basis of Morphogenesis' (1952)", layer: "evidence", type: "evidence",
          data: { domain: "developmental_biology_morphogenesis", source_type: "document", uncertainty: 0.12, tags: ["turing","morphogenesis","reaction-diffusion","1952"] } },
        { id: "ev-levin-bioelectric-2021", label: "Levin — bioelectric signaling in morphogenesis and cognition (2021)", layer: "evidence", type: "evidence",
          data: { domain: "developmental_biology_morphogenesis", source_type: "document", uncertainty: 0.38, tags: ["levin","bioelectric","planaria","morphogenetic-field"] } },
        { id: "ev-wolpert-positional-info-1969", label: "Wolpert — positional information and pattern formation (1969)", layer: "evidence", type: "evidence",
          data: { domain: "developmental_biology_morphogenesis", source_type: "document", uncertainty: 0.09, tags: ["wolpert","positional-information","french-flag","gradient"] } },
        // ── Optimization and Control (hybrid) ─────────────────────────────────
        { id: "ev-bellman-dp-1957", label: "Bellman — 'Dynamic Programming' (1957)", layer: "evidence", type: "evidence",
          data: { domain: "optimization_and_control", source_type: "document", uncertainty: 0.02, tags: ["bellman","dynamic-programming","optimal-substructure","1957"] } },
        { id: "ev-pontryagin-maxprinciple", label: "Pontryagin maximum principle — optimal control (1956)", layer: "evidence", type: "evidence",
          data: { domain: "optimization_and_control", source_type: "document", uncertainty: 0.03, tags: ["pontryagin","maximum-principle","control","Hamiltonian"] } },
        { id: "ev-villani-optimal-transport-2008", label: "Villani 'Optimal Transport: Old and New' — Wasserstein (2008)", layer: "evidence", type: "evidence",
          data: { domain: "optimization_and_control", source_type: "document", uncertainty: 0.07, tags: ["villani","optimal-transport","wasserstein","2008"] } },
        // ── Algebraic Structures (hybrid) ──────────────────────────────────────
        { id: "ev-reed-solomon-1960", label: "Reed & Solomon — polynomial error-correcting codes (1960)", layer: "evidence", type: "evidence",
          data: { domain: "algebraic_structures", source_type: "document", uncertainty: 0.02, tags: ["reed","solomon","error-correcting","finite-field","codes","1960"] } },
        { id: "ev-galois-groups", label: "Galois theory — field extensions and polynomial solvability", layer: "evidence", type: "evidence",
          data: { domain: "algebraic_structures", source_type: "document", uncertainty: 0.04, tags: ["galois","group","field-extension","solvability","permutation"] } },
        { id: "ev-finite-field-construction", label: "Wedderburn theorem — finite fields Galois field GF(q)", layer: "evidence", type: "evidence",
          data: { domain: "algebraic_structures", source_type: "document", uncertainty: 0.03, tags: ["wedderburn","finite-field","GF","galois-field","coding"] } },
        // ── Disaster Response Operations (speculative) ─────────────────────────
        { id: "ev-fema-nims-2008", label: "FEMA NIMS — National Incident Management System v2008", layer: "evidence", type: "evidence",
          data: { domain: "disaster_response_operations", source_type: "document", uncertainty: 0.22, tags: ["fema","NIMS","ICS","incident-command","response"] } },
        { id: "ev-katrina-response-failure-2006", label: "GAO Hurricane Katrina response failure analysis (2006)", layer: "evidence", type: "evidence",
          data: { domain: "disaster_response_operations", source_type: "document", uncertainty: 0.28, tags: ["katrina","GAO","response","failure","coordination"] } },
        { id: "ev-mcr-triage-resource-routing", label: "Mass casualty resource routing — tiered triage literature", layer: "evidence", type: "evidence",
          data: { domain: "disaster_response_operations", source_type: "document", uncertainty: 0.41, tags: ["mass-casualty","triage","resource-routing","surge"] } },
        // ── Public Health Coordination (speculative) ───────────────────────────
        { id: "ev-cdc-phep-capabilities", label: "CDC Public Health Emergency Preparedness capabilities (2011)", layer: "evidence", type: "evidence",
          data: { domain: "public_health_coordination", source_type: "document", uncertainty: 0.31, tags: ["CDC","PHEP","emergency","preparedness","capabilities"] } },
        { id: "ev-who-ihr-core-capacities", label: "WHO IHR core capacity requirements — surveillance and response", layer: "evidence", type: "evidence",
          data: { domain: "public_health_coordination", source_type: "document", uncertainty: 0.26, tags: ["WHO","IHR","core-capacity","surveillance","response"] } },
        // ── Industrial Quality Control (speculative) ───────────────────────────
        { id: "ev-shewhart-control-charts-1931", label: "Shewhart — 'Economic Control of Quality of Manufactured Product' (1931)", layer: "evidence", type: "evidence",
          data: { domain: "industrial_quality_control", source_type: "document", uncertainty: 0.06, tags: ["shewhart","control-chart","SPC","quality","1931"] } },
        { id: "ev-six-sigma-motorola-1986", label: "Motorola Six Sigma methodology — DMAIC framework (1986)", layer: "evidence", type: "evidence",
          data: { domain: "industrial_quality_control", source_type: "document", uncertainty: 0.18, tags: ["six-sigma","motorola","DMAIC","defect","quality"] } },
        { id: "ev-toyota-andon-tps", label: "Toyota Production System — andon cord and jidoka", layer: "evidence", type: "evidence",
          data: { domain: "industrial_quality_control", source_type: "document", uncertainty: 0.14, tags: ["toyota","andon","TPS","jidoka","quality"] } },
        // ── Supply Chain Resilience (speculative) ──────────────────────────────
        { id: "ev-sheffi-supply-disruption-2005", label: "Sheffi 'The Resilient Enterprise' — supply chain disruption taxonomy", layer: "evidence", type: "evidence",
          data: { domain: "supply_chain_resilience", source_type: "document", uncertainty: 0.29, tags: ["sheffi","resilience","disruption","supply-chain","enterprise"] } },
        { id: "ev-covid-ppe-shortage-2020", label: "COVID-19 PPE supply shortage — N95 stockpile collapse (2020)", layer: "evidence", type: "evidence",
          data: { domain: "supply_chain_resilience", source_type: "document", uncertainty: 0.24, tags: ["COVID19","PPE","N95","shortage","supply-chain"] } },
        { id: "ev-jit-vs-resilience-tradeoff", label: "Just-in-time vs. safety-stock resilience tradeoff literature", layer: "evidence", type: "evidence",
          data: { domain: "supply_chain_resilience", source_type: "document", uncertainty: 0.35, tags: ["JIT","just-in-time","safety-stock","resilience","tradeoff"] } },
        // ── Expert Preservation (speculative) ─────────────────────────────────
        { id: "ev-polanyi-tacit-1966", label: "Polanyi — 'The Tacit Dimension' (1966)", layer: "evidence", type: "evidence",
          data: { domain: "expert_preservation", source_type: "document", uncertainty: 0.09, tags: ["polanyi","tacit","dimension","knowledge","1966"] } },
        { id: "ev-nonaka-knowledge-creation", label: "Nonaka & Takeuchi — 'Knowledge-Creating Company' SECI model (1995)", layer: "evidence", type: "evidence",
          data: { domain: "expert_preservation", source_type: "document", uncertainty: 0.19, tags: ["nonaka","takeuchi","SECI","socialization","externalization","1995"] } },
        { id: "ev-retirement-knowledge-gap", label: "SHRM workforce knowledge loss at expert retirement — survey", layer: "evidence", type: "evidence",
          data: { domain: "expert_preservation", source_type: "document", uncertainty: 0.44, tags: ["retirement","knowledge-gap","succession","SHRM","tacit"] } },
        // ── Experimental Design (hybrid) ──────────────────────────────────────
        { id: "ev-fisher-doe-1935", label: "Fisher — 'Design of Experiments' (1935)", layer: "evidence", type: "evidence",
          data: { domain: "experimental_design_and_measurement", source_type: "document", uncertainty: 0.04, tags: ["fisher","design-of-experiments","randomization","1935"] } },
        { id: "ev-bradford-hill-1965", label: "Bradford Hill criteria for causal inference in epidemiology (1965)", layer: "evidence", type: "evidence",
          data: { domain: "experimental_design_and_measurement", source_type: "document", uncertainty: 0.07, tags: ["bradford-hill","causation","criteria","epidemiology","1965"] } },
        { id: "ev-campbell-internal-validity", label: "Campbell & Stanley — internal vs. external validity (1963)", layer: "evidence", type: "evidence",
          data: { domain: "experimental_design_and_measurement", source_type: "document", uncertainty: 0.06, tags: ["campbell","stanley","validity","experimental","1963"] } },
        // ── Scientific Model Transfer (speculative) ────────────────────────────
        { id: "ev-kuhn-paradigm-1962", label: "Kuhn — 'Structure of Scientific Revolutions' paradigm shift (1962)", layer: "evidence", type: "evidence",
          data: { domain: "scientific_model_transfer", source_type: "document", uncertainty: 0.19, tags: ["kuhn","paradigm","revolution","incommensurability","1962"] } },
        { id: "ev-gentner-structural-mapping-1983", label: "Gentner — structure-mapping theory of analogy (1983)", layer: "evidence", type: "evidence",
          data: { domain: "scientific_model_transfer", source_type: "document", uncertainty: 0.12, tags: ["gentner","structure-mapping","analogy","SMT","1983"] } },
      ],
      edges: [],
    },

    context: {
      nodes: [
        // ── Drug Discovery ─────────────────────────────────────────────────────
        { id: "dec-trial-approval-2024", label: "Phase II CNS cohort expansion — deferred", layer: "context", type: "context",
          data: { question: "Should Phase II expand to CNS-metastatic NSCLC?", outcome: "deferred", is_exception: true, domain: "drug_discovery" } },
        { id: "prec-cns-deferral-2022", label: "CNS deferral precedent — AMG-224 (2022)", layer: "context", type: "Precedent",
          data: { confidence: 0.82, invocation_count: 1, domain: "drug_discovery" } },
        { id: "dec-adagrasib-combination", label: "Adagrasib + cetuximab combination — approved", layer: "context", type: "context",
          data: { question: "Should adagrasib be combined with cetuximab for KRAS G12C colorectal?", outcome: "approved", domain: "drug_discovery" } },
        // ── Fukushima ──────────────────────────────────────────────────────────
        { id: "dec-seawall-deferral-2008", label: "Seawall upgrade deferred — TEPCO 2008", layer: "context", type: "context",
          data: { question: "Should seawall be upgraded given 15.7m tsunami estimate?", outcome: "deferred", is_exception: false, domain: "fukushima_governance" } },
        { id: "dec-generator-relocation-deferred", label: "Generator relocation to high ground — deferred", layer: "context", type: "context",
          data: { question: "Should backup diesel generators be moved above 10m elevation?", outcome: "deferred", domain: "fukushima_governance" } },
        { id: "dec-onagawa-seawall-1967", label: "Onagawa 14.8m seawall — Hirai decision 1967", layer: "context", type: "context",
          data: { question: "What height seawall should Onagawa nuclear plant have?", outcome: "approved", is_exception: true, domain: "fukushima_governance" } },
        // ── EUV ───────────────────────────────────────────────────────────────
        { id: "dec-tin-over-xenon-2007", label: "Tin plasma selected over xenon — ASML 2007", layer: "context", type: "context",
          data: { question: "Should EUV source use tin or xenon plasma?", outcome: "approved", is_exception: false, domain: "euv_lithography" } },
        { id: "dec-cymer-acquisition-2012", label: "Cymer acquisition — ASML 2012 ($2.5B)", layer: "context", type: "context",
          data: { question: "Should ASML acquire Cymer to internalize EUV source knowledge?", outcome: "approved", is_exception: true, domain: "euv_lithography" } },
        { id: "dec-highna-euv-program", label: "High-NA EUV program launch — ASML 2016", layer: "context", type: "context",
          data: { question: "Should ASML begin High-NA EUV development for sub-2nm nodes?", outcome: "approved", domain: "euv_lithography" } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "dec-mcas-single-sensor", label: "MCAS single-sensor design — Boeing approved", layer: "context", type: "context",
          data: { question: "Should MCAS rely on single AOA sensor input?", outcome: "approved", is_exception: false, domain: "aviation_safety" } },
        { id: "dec-pierson-grounding-request", label: "Pierson grounding request — classified as HR matter", layer: "context", type: "context",
          data: { question: "Should 737 MAX production halt given workforce safety concerns?", outcome: "rejected", is_exception: true, domain: "aviation_safety" } },
        { id: "dec-challenger-launch-proceed", label: "STS-51L Challenger launch proceed — 1986", layer: "context", type: "context",
          data: { question: "Should launch proceed at 28°F given O-ring temperature concerns?", outcome: "approved", is_exception: true, domain: "aviation_safety" } },
        { id: "prec-dc10-decompression-1974", label: "DC-10 Turkish Airlines decompression precedent", layer: "context", type: "Precedent",
          data: { confidence: 0.77, invocation_count: 0, domain: "aviation_safety" } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "dec-glasgow-coal-phaseout", label: "Glasgow COP26 coal phase-down language — weakened", layer: "context", type: "context",
          data: { question: "Should COP26 commit to coal phase-out or phase-down?", outcome: "phase-down", is_exception: false, domain: "climate_policy" } },
        { id: "dec-paris-15c-target", label: "Paris Agreement 1.5°C target adoption", layer: "context", type: "context",
          data: { question: "Should Paris Agreement target 1.5°C or 2°C warming?", outcome: "approved", is_exception: true, domain: "climate_policy" } },
        // ── Pandemic ──────────────────────────────────────────────────────────
        { id: "dec-who-pheic-jan30", label: "WHO PHEIC declaration — 30 Jan 2020", layer: "context", type: "context",
          data: { question: "Should WHO declare COVID-19 a Public Health Emergency of International Concern?", outcome: "approved", domain: "pandemic_governance" } },
        { id: "dec-who-aerosol-guidance", label: "WHO aerosol transmission guidance update — July 2020", layer: "context", type: "context",
          data: { question: "Should WHO update guidance to include aerosol transmission?", outcome: "deferred", is_exception: false, domain: "pandemic_governance" } },
        // ── Surgical Robotics ──────────────────────────────────────────────────
        { id: "dec-davinci-haptic-omission", label: "Haptic force feedback omitted from da Vinci — 1999", layer: "context", type: "context",
          data: { question: "Should da Vinci Si include haptic force feedback?", outcome: "rejected", domain: "surgical_robotics" } },
      ],
      edges: [
        { source: "dec-trial-approval-2024", target: "ev-bbb-assay-results", relation: "JUSTIFIED_BY" },
        { source: "dec-trial-approval-2024", target: "ev-codebreak100-trial", relation: "JUSTIFIED_BY" },
        { source: "dec-seawall-deferral-2008", target: "ev-tepco-2008-assessment", relation: "JUSTIFIED_BY" },
        { source: "dec-onagawa-seawall-1967", target: "ev-hirai-onagawa-design", relation: "JUSTIFIED_BY" },
        { source: "dec-tin-over-xenon-2007", target: "ev-prepulse-asml-2003", relation: "JUSTIFIED_BY" },
        { source: "dec-mcas-single-sensor", target: "ev-737max-fmea-boeing", relation: "JUSTIFIED_BY" },
        { source: "dec-pierson-grounding-request", target: "ev-pierson-letter-2019", relation: "JUSTIFIED_BY" },
        { source: "dec-challenger-launch-proceed", target: "ev-challenger-oring-tests", relation: "CONTRADICTS" },
        { source: "dec-glasgow-coal-phaseout", target: "ev-glasgow-ndc-gap-2021", relation: "JUSTIFIED_BY" },
        { source: "dec-paris-15c-target", target: "ev-ipcc-ar6-spm", relation: "JUSTIFIED_BY" },
        { source: "dec-who-pheic-jan30", target: "ev-who-pheic-delay-2020", relation: "JUSTIFIED_BY" },
        { source: "dec-who-aerosol-guidance", target: "ev-aerosol-zhang-2020", relation: "CONTRADICTS" },
        { source: "dec-adagrasib-combination", target: "ev-adagrasib-phase1", relation: "JUSTIFIED_BY" },
      ],
    },

    knowledge: {
      nodes: [
        // ── Drug Discovery — molecular ─────────────────────────────────────────
        { id: "ent-KRAS",   label: "KRAS G12C",        layer: "knowledge", type: "knowledge",
          data: { entity_type: "protein", domain: "drug_discovery", attributes: { gene: "KRAS", mutation: "G12C" } } },
        { id: "ent-RAF",    label: "RAF kinase",       layer: "knowledge", type: "knowledge",
          data: { entity_type: "protein", domain: "drug_discovery" } },
        { id: "ent-MEK",    label: "MEK",              layer: "knowledge", type: "knowledge",
          data: { entity_type: "protein", domain: "drug_discovery" } },
        { id: "ent-ERK",    label: "ERK",              layer: "knowledge", type: "knowledge",
          data: { entity_type: "protein", domain: "drug_discovery" } },
        { id: "ent-AMG510", label: "Sotorasib",        layer: "knowledge", type: "knowledge",
          data: { entity_type: "compound", domain: "drug_discovery", attributes: { fda_approved: true } } },
        { id: "ent-MRTX849",label: "Adagrasib",        layer: "knowledge", type: "knowledge",
          data: { entity_type: "compound", domain: "drug_discovery", attributes: { fda_approved: true } } },
        { id: "ent-TP53",   label: "TP53 (p53)",       layer: "knowledge", type: "knowledge",
          data: { entity_type: "protein", domain: "drug_discovery", attributes: { role: "tumor suppressor" } } },
        { id: "ent-cetuximab", label: "Cetuximab (EGFR mAb)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "biologic", domain: "drug_discovery" } },
        { id: "mech-KRAS-activates-RAF",   label: "KRAS activates RAF",       layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.97, domain: "drug_discovery" } },
        { id: "mech-RAF-activates-MEK",    label: "RAF phosphorylates MEK",   layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.96, domain: "drug_discovery" } },
        { id: "mech-MEK-activates-ERK",    label: "MEK activates ERK",        layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.98, domain: "drug_discovery" } },
        { id: "mech-AMG510-inhibits-KRAS", label: "AMG510 inhibits KRAS G12C", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "inhibitory", confidence: 0.94, domain: "drug_discovery" } },
        { id: "hyp-combination-resistance", label: "Combination therapy delays G12C resistance", layer: "knowledge", type: "Hypothesis",
          data: { status: "under_investigation", evidence_for: ["ev-adagrasib-phase1"], domain: "drug_discovery" } },
        // ── Fukushima ──────────────────────────────────────────────────────────
        { id: "ent-fukushima-plant", label: "Fukushima Daiichi NPP", layer: "knowledge", type: "knowledge",
          data: { entity_type: "facility", domain: "fukushima_governance", attributes: { reactors: 6, seawall_height_m: 5.7 } } },
        { id: "ent-onagawa-plant", label: "Onagawa Nuclear Plant", layer: "knowledge", type: "knowledge",
          data: { entity_type: "facility", domain: "fukushima_governance", attributes: { seawall_height_m: 14.8, operator: "Tohoku Electric" } } },
        { id: "ent-seawall-fukushima", label: "Fukushima seawall (5.7m)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "infrastructure", domain: "fukushima_governance", attributes: { height_m: 5.7, deficit_m: 9.8 } } },
        { id: "ent-jogan-event", label: "Jogan earthquake 869 AD", layer: "knowledge", type: "knowledge",
          data: { entity_type: "historical_event", domain: "fukushima_governance", attributes: { year: 869 } } },
        { id: "mech-tsunami-sbo", label: "Tsunami → station blackout", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.95, domain: "fukushima_governance" } },
        { id: "mech-sbo-meltdown", label: "Station blackout → core meltdown", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.99, domain: "fukushima_governance" } },
        // ── EUV Lithography ────────────────────────────────────────────────────
        { id: "ent-euv-photon", label: "EUV photon 13.5nm", layer: "knowledge", type: "knowledge",
          data: { entity_type: "physical_entity", domain: "euv_lithography", attributes: { wavelength_nm: 13.5 } } },
        { id: "ent-tin-source", label: "LPP tin plasma EUV source", layer: "knowledge", type: "knowledge",
          data: { entity_type: "component", domain: "euv_lithography", attributes: { droplets_per_sec: 50000 } } },
        { id: "ent-highna-optics", label: "High-NA EUV optical column (0.55 NA)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "component", domain: "euv_lithography", attributes: { NA: 0.55, resolution_nm: 8 } } },
        { id: "mech-laser-plasma", label: "CO2 laser → tin plasma → 13.5nm", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.96, domain: "euv_lithography" } },
        { id: "mech-sn-contamination", label: "Sn contamination → mirror degradation", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.91, domain: "euv_lithography" } },
        { id: "mech-prepulse-droplet", label: "Pre-pulse flattens tin droplet → efficient plasma", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.93, domain: "euv_lithography" } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "ent-737max", label: "Boeing 737 MAX", layer: "knowledge", type: "knowledge",
          data: { entity_type: "aircraft", domain: "aviation_safety", attributes: { first_flight: 2016, fatalities: 346 } } },
        { id: "ent-mcas", label: "MCAS (Maneuvering Characteristics Augmentation)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "software_system", domain: "aviation_safety", attributes: { single_sensor: true, pilot_notified: false } } },
        { id: "ent-aoa-sensor", label: "Angle-of-Attack (AOA) sensor", layer: "knowledge", type: "knowledge",
          data: { entity_type: "sensor", domain: "aviation_safety", attributes: { redundancy: "single", failure_mode: "erroneous input" } } },
        { id: "ent-challenger", label: "Space Shuttle Challenger STS-51L", layer: "knowledge", type: "knowledge",
          data: { entity_type: "spacecraft", domain: "aviation_safety", attributes: { year: 1986, fatalities: 7 } } },
        { id: "mech-mcas-runaway", label: "Erroneous AOA → MCAS runaway → loss of control", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.99, domain: "aviation_safety" } },
        { id: "mech-oring-brittle", label: "Low temp → O-ring brittle → hot gas blowby", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.97, domain: "aviation_safety" } },
        { id: "mech-authority-override", label: "Authority override of calibrated dissent", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "structural", confidence: 0.91, domain: "aviation_safety" } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "ent-co2-concentration", label: "Atmospheric CO₂ (ppm)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "measurement", domain: "climate_policy", attributes: { value_2023: 421, preindustrial: 280, unit: "ppm" } } },
        { id: "ent-arctic-amplification", label: "Arctic amplification feedback", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mechanism_entity", domain: "climate_policy", attributes: { amplification_factor: 3.0 } } },
        { id: "ent-tipping-points", label: "Climate tipping point cascade", layer: "knowledge", type: "knowledge",
          data: { entity_type: "systemic_risk", domain: "climate_policy", attributes: { count: 16, interacting: true } } },
        { id: "mech-ghg-forcing", label: "GHG concentration → radiative forcing → warming", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.98, domain: "climate_policy" } },
        { id: "mech-ndc-gap", label: "NDC pledges → 2.4°C trajectory (gap from 1.5°C)", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "structural", confidence: 0.89, domain: "climate_policy" } },
        { id: "hyp-1p5-achievable", label: "1.5°C achievable with 50% emissions cut by 2030", layer: "knowledge", type: "Hypothesis",
          data: { status: "contested", domain: "climate_policy" } },
        // ── Surgical Robotics ──────────────────────────────────────────────────
        { id: "ent-davinci-xi", label: "da Vinci Xi surgical system", layer: "knowledge", type: "knowledge",
          data: { entity_type: "device", domain: "surgical_robotics", attributes: { arms: 4, haptic_feedback: false, fda_cleared: true } } },
        { id: "ent-or-governance", label: "OR governance protocol (WHO checklist)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "protocol", domain: "surgical_robotics", attributes: { compliance: 0.72 } } },
        { id: "mech-teleop-latency", label: "Teleoperation latency → force perception error", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.86, domain: "surgical_robotics" } },
        // ── Pandemic Governance ────────────────────────────────────────────────
        { id: "ent-sars-cov2", label: "SARS-CoV-2 virus", layer: "knowledge", type: "knowledge",
          data: { entity_type: "pathogen", domain: "pandemic_governance", attributes: { R0: 2.5, transmission: "aerosol+contact" } } },
        { id: "ent-who-ihr", label: "WHO International Health Regulations (IHR)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "governance_framework", domain: "pandemic_governance", attributes: { adopted: 2005 } } },
        { id: "mech-aerosol-transmission", label: "Aerosol droplet nuclei → indoor airborne spread", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.92, domain: "pandemic_governance" } },
        { id: "mech-reporting-delay-spread", label: "Reporting delay → missed containment window", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.88, domain: "pandemic_governance" } },
        // ── Cross-domain structural mechanisms ────────────────────────────────
        { id: "mech-org-silence-failure", label: "Organizational silence → systemic failure", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "structural", confidence: 0.93, domain: "fukushima_governance" } },
        { id: "mech-calibration-discount", label: "Political discount of calibrated expertise", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "structural", confidence: 0.91, domain: "climate_policy" } },
        // ── Extreme Environments ───────────────────────────────────────────────
        { id: "ent-oring-joint", label: "Solid Rocket Booster O-ring joint", layer: "knowledge", type: "knowledge",
          data: { entity_type: "component", domain: "extreme_environments", attributes: { material: "VITON", temp_min_F: 50 } } },
        { id: "ent-deviance-normalization", label: "Normalization of deviance (Vaughan)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "extreme_environments", attributes: { source: "Vaughan 1996" } } },
        { id: "mech-schedule-pressure-risk-acceptance", label: "Schedule pressure → incremental risk acceptance → failure", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "structural", confidence: 0.92, domain: "extreme_environments" } },
        { id: "hyp-cold-soak-failure-threshold", label: "O-ring failure probability >1% below 53°F", layer: "knowledge", type: "Hypothesis",
          data: { status: "confirmed_post_hoc", domain: "extreme_environments" } },
        // ── Semiconductor Hardware ─────────────────────────────────────────────
        { id: "ent-process-window", label: "Plasma etch process window", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "semiconductor_hardware", attributes: { type: "bounded_parameter_space" } } },
        { id: "ent-n3-node", label: "TSMC N3 3nm process node", layer: "knowledge", type: "knowledge",
          data: { entity_type: "technology_node", domain: "semiconductor_hardware", attributes: { transistors_per_mm2: 292000000 } } },
        { id: "mech-process-drift", label: "Tool aging → parameter drift → yield loss", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.88, domain: "semiconductor_hardware" } },
        { id: "mech-yield-governance", label: "In-line SPC gates yield-reject lots before test", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "procedural", confidence: 0.85, domain: "semiconductor_hardware" } },
        // ── Mathematics / Category Theory ──────────────────────────────────────
        { id: "ent-functor", label: "Functor (structure-preserving map)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "mathematics_category_theory", attributes: { preserves: "objects and morphisms" } } },
        { id: "ent-natural-transformation", label: "Natural transformation between functors", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "mathematics_category_theory", attributes: { commutativity: "required" } } },
        { id: "ent-adjunction", label: "Adjunction (left-right functor pair)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "mathematics_category_theory" } },
        { id: "mech-transfer-validity", label: "Natural transformation commutativity → valid transfer", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "formal", confidence: 1.0, domain: "mathematics_category_theory" } },
        // ── Causality and Complex Systems ──────────────────────────────────────
        { id: "ent-dag-causal", label: "Directed Acyclic Graph (DAG)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "causality_and_complex_systems", attributes: { type: "causal_graph" } } },
        { id: "ent-do-calculus", label: "Pearl do-calculus intervention operator", layer: "knowledge", type: "knowledge",
          data: { entity_type: "formal_method", domain: "causality_and_complex_systems" } },
        { id: "mech-confounding-adjustment", label: "Backdoor adjustment → unbiased causal estimate", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "statistical", confidence: 0.95, domain: "causality_and_complex_systems" } },
        // ── Information Theory ─────────────────────────────────────────────────
        { id: "ent-shannon-entropy", label: "Shannon entropy H(X)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_quantity", domain: "information_theory", attributes: { formula: "H = -Σ p log p" } } },
        { id: "ent-channel-capacity", label: "Channel capacity C = max I(X;Y)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_quantity", domain: "information_theory" } },
        { id: "mech-noisy-channel-coding", label: "Rate < capacity → arbitrarily reliable communication", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "theoretical", confidence: 1.0, domain: "information_theory" } },
        // ── Graph Theory and Networks ──────────────────────────────────────────
        { id: "ent-adjacency-matrix", label: "Graph adjacency matrix A", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "graph_theory_and_networks" } },
        { id: "ent-spectral-gap", label: "Spectral gap (λ₁ - λ₂)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_quantity", domain: "graph_theory_and_networks", attributes: { relates_to: "mixing_time" } } },
        { id: "mech-r0-eigenvalue", label: "R₀ = dominant eigenvalue of contact graph", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "mathematical", confidence: 0.89, domain: "graph_theory_and_networks" } },
        // ── Translational Biomedicine ──────────────────────────────────────────
        { id: "ent-bench-to-bedside-gap", label: "Translational gap (in vitro → clinical)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "translational_biomedicine", attributes: { attrition_rate: 0.92 } } },
        { id: "ent-admet-profile", label: "ADMET profile (absorption/distribution/metabolism/excretion/toxicity)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "translational_biomedicine" } },
        { id: "mech-bioavailability-fail", label: "Poor ADMET → 90% clinical trial failure", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "statistical", confidence: 0.88, domain: "translational_biomedicine" } },
        // ── Developmental Biology / Morphogenesis ──────────────────────────────
        { id: "ent-turing-pattern", label: "Turing reaction-diffusion pattern", layer: "knowledge", type: "knowledge",
          data: { entity_type: "phenomenon", domain: "developmental_biology_morphogenesis", attributes: { source: "Turing 1952" } } },
        { id: "ent-morphogen-gradient", label: "Morphogen concentration gradient", layer: "knowledge", type: "knowledge",
          data: { entity_type: "biological_entity", domain: "developmental_biology_morphogenesis" } },
        { id: "mech-positional-information", label: "Morphogen gradient → positional identity → pattern", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.91, domain: "developmental_biology_morphogenesis" } },
        // ── Optimization and Control ───────────────────────────────────────────
        { id: "ent-value-function", label: "Bellman value function V*(s)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "optimization_and_control" } },
        { id: "ent-wasserstein-distance", label: "Wasserstein distance (earth mover's distance)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_quantity", domain: "optimization_and_control", attributes: { type: "optimal_transport_cost" } } },
        { id: "mech-bellman-optimality", label: "Recursive Bellman equation → globally optimal policy", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "formal", confidence: 1.0, domain: "optimization_and_control" } },
        // ── Algebraic Structures ───────────────────────────────────────────────
        { id: "ent-galois-group", label: "Galois group of polynomial", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "algebraic_structures" } },
        { id: "ent-rs-codeword", label: "Reed-Solomon codeword over GF(q)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "mathematical_object", domain: "algebraic_structures", attributes: { min_distance: "n-k+1" } } },
        { id: "mech-rs-error-correction", label: "Polynomial evaluation → error detection/correction", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "algebraic", confidence: 1.0, domain: "algebraic_structures" } },
        // ── Disaster Response Operations ───────────────────────────────────────
        { id: "ent-ics-structure", label: "Incident Command System (ICS)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "organizational_structure", domain: "disaster_response_operations", attributes: { span_of_control: "3-7" } } },
        { id: "mech-cascade-failure-response", label: "Single-command failure → response fragmentation", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.82, domain: "disaster_response_operations" } },
        // ── Public Health Coordination ─────────────────────────────────────────
        { id: "ent-ihr-core-capacity", label: "IHR Core Capacity requirements", layer: "knowledge", type: "knowledge",
          data: { entity_type: "regulatory_framework", domain: "public_health_coordination", attributes: { domains: 8 } } },
        { id: "mech-surveillance-alert", label: "Event-based surveillance → early warning → containment", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.79, domain: "public_health_coordination" } },
        // ── Industrial Quality Control ─────────────────────────────────────────
        { id: "ent-shewhart-chart", label: "Shewhart X-bar R control chart", layer: "knowledge", type: "knowledge",
          data: { entity_type: "tool", domain: "industrial_quality_control", attributes: { sigma_limit: 3 } } },
        { id: "mech-spc-drift-detection", label: "Process drift → control limit breach → assignable cause", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "statistical", confidence: 0.92, domain: "industrial_quality_control" } },
        // ── Supply Chain Resilience ────────────────────────────────────────────
        { id: "ent-single-source-node", label: "Single-source bottleneck node", layer: "knowledge", type: "knowledge",
          data: { entity_type: "network_concept", domain: "supply_chain_resilience" } },
        { id: "mech-jit-fragility", label: "JIT inventory → zero buffer → demand shock → failure", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.88, domain: "supply_chain_resilience" } },
        // ── Expert Preservation ────────────────────────────────────────────────
        { id: "ent-tacit-knowledge", label: "Tacit knowledge (Polanyi)", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "expert_preservation", attributes: { codifiable: false, source: "Polanyi 1966" } } },
        { id: "mech-expertise-retirement-loss", label: "Expert retirement → knowledge loss → capability degradation", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "causal", confidence: 0.91, domain: "expert_preservation" } },
        // ── Experimental Design ────────────────────────────────────────────────
        { id: "ent-rct-design", label: "Randomized controlled trial design", layer: "knowledge", type: "knowledge",
          data: { entity_type: "methodology", domain: "experimental_design_and_measurement", attributes: { gold_standard: true } } },
        { id: "mech-randomization-confound", label: "Randomization → balanced confounders → valid causal claim", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "statistical", confidence: 0.97, domain: "experimental_design_and_measurement" } },
        // ── Scientific Model Transfer ──────────────────────────────────────────
        { id: "ent-abstraction-invariant", label: "Structural invariant across model transfer", layer: "knowledge", type: "knowledge",
          data: { entity_type: "concept", domain: "scientific_model_transfer" } },
        { id: "mech-paradigm-incommensurability", label: "Paradigm shift → loss of cross-paradigm translation", layer: "knowledge", type: "Mechanism",
          data: { mechanism_type: "conceptual", confidence: 0.78, domain: "scientific_model_transfer" } },
      ],
      edges: [
        // Drug discovery
        { source: "ent-KRAS",   target: "mech-KRAS-activates-RAF",   relation: "HAS_MECHANISM" },
        { source: "mech-KRAS-activates-RAF",   target: "ent-RAF",    relation: "TARGETS" },
        { source: "ent-RAF",    target: "mech-RAF-activates-MEK",    relation: "HAS_MECHANISM" },
        { source: "mech-RAF-activates-MEK",    target: "ent-MEK",   relation: "TARGETS" },
        { source: "ent-MEK",    target: "mech-MEK-activates-ERK",    relation: "HAS_MECHANISM" },
        { source: "mech-MEK-activates-ERK",    target: "ent-ERK",   relation: "TARGETS" },
        { source: "ent-AMG510", target: "mech-AMG510-inhibits-KRAS", relation: "HAS_MECHANISM" },
        { source: "mech-AMG510-inhibits-KRAS", target: "ent-KRAS",  relation: "TARGETS" },
        { source: "ent-MRTX849", target: "ent-KRAS", relation: "INHIBITS" },
        { source: "ent-cetuximab", target: "ent-MRTX849", relation: "SYNERGIZES_WITH" },
        // Fukushima
        { source: "ent-fukushima-plant", target: "mech-tsunami-sbo", relation: "HAS_MECHANISM" },
        { source: "mech-tsunami-sbo", target: "mech-sbo-meltdown", relation: "TRIGGERS" },
        { source: "ent-onagawa-plant", target: "ent-seawall-fukushima", relation: "CONTRASTS_WITH" },
        // EUV
        { source: "ent-tin-source", target: "mech-laser-plasma", relation: "HAS_MECHANISM" },
        { source: "mech-laser-plasma", target: "ent-euv-photon", relation: "PRODUCES" },
        { source: "ent-tin-source", target: "mech-sn-contamination", relation: "HAS_MECHANISM" },
        { source: "ent-tin-source", target: "mech-prepulse-droplet", relation: "HAS_MECHANISM" },
        { source: "ent-highna-optics", target: "ent-euv-photon", relation: "USES" },
        // Aviation
        { source: "ent-mcas", target: "mech-mcas-runaway", relation: "HAS_MECHANISM" },
        { source: "ent-aoa-sensor", target: "mech-mcas-runaway", relation: "TRIGGERS" },
        { source: "mech-mcas-runaway", target: "ent-737max", relation: "AFFECTED" },
        { source: "ent-challenger", target: "mech-oring-brittle", relation: "CAUSED_BY" },
        { source: "mech-authority-override", target: "mech-mcas-runaway", relation: "ENABLES" },
        { source: "mech-authority-override", target: "mech-oring-brittle", relation: "ENABLES" },
        // Climate
        { source: "ent-co2-concentration", target: "mech-ghg-forcing", relation: "DRIVES" },
        { source: "mech-ghg-forcing", target: "ent-tipping-points", relation: "APPROACHES" },
        { source: "mech-ndc-gap", target: "ent-tipping-points", relation: "RISKS" },
        // Pandemic
        { source: "ent-sars-cov2", target: "mech-aerosol-transmission", relation: "HAS_MECHANISM" },
        { source: "mech-reporting-delay-spread", target: "ent-sars-cov2", relation: "AMPLIFIED_BY" },
        // Cross-domain
        { source: "mech-authority-override", target: "mech-org-silence-failure", relation: "CAUSES" },
        { source: "mech-org-silence-failure", target: "mech-tsunami-sbo", relation: "ENABLES" },
        { source: "mech-calibration-discount", target: "mech-ndc-gap", relation: "PERPETUATES" },
      ],
    },

    goal: {
      nodes: [
        // ── Drug Discovery ─────────────────────────────────────────────────────
        { id: "goal-reduce-tumor-burden", label: "Reduce KRAS G12C tumour burden ≥40% ORR", layer: "goal", type: "goal",
          data: { priority: 0.95, status: "active", metric: "objective_response_rate", domain: "drug_discovery" } },
        { id: "goal-patient-safety", label: "Maintain acceptable safety profile", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "active", metric: "grade3_adverse_events", domain: "drug_discovery" } },
        { id: "constraint-cns-safety-gate", label: "BBB uncertainty <0.4 required for CNS", layer: "goal", type: "Constraint",
          data: { constraint_type: "hard", domain: "drug_discovery" } },
        { id: "goal-resistance-prevention", label: "Delay acquired resistance to KRAS inhibition", layer: "goal", type: "goal",
          data: { priority: 0.80, status: "active", domain: "drug_discovery" } },
        // ── Fukushima ──────────────────────────────────────────────────────────
        { id: "goal-nuclear-safety", label: "Prevent core damage at Fukushima Daiichi", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "failed", domain: "fukushima_governance" } },
        { id: "constraint-uncertainty-gate", label: "Seawall risk deferral requires uncertainty <0.4", layer: "goal", type: "Constraint",
          data: { constraint_type: "hard", domain: "fukushima_governance" } },
        { id: "goal-onagawa-safety", label: "Zero reactor failures at Onagawa (achieved)", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "achieved", domain: "fukushima_governance" } },
        // ── EUV ───────────────────────────────────────────────────────────────
        { id: "goal-euv-throughput", label: "Achieve >100 wafers/hour EUV throughput", layer: "goal", type: "goal",
          data: { priority: 0.9, status: "achieved", domain: "euv_lithography" } },
        { id: "goal-mirror-lifetime", label: "Extend collector mirror lifetime >1 year", layer: "goal", type: "goal",
          data: { priority: 0.85, status: "active", domain: "euv_lithography" } },
        { id: "goal-highna-readiness", label: "High-NA EUV production-ready by 2025", layer: "goal", type: "goal",
          data: { priority: 0.88, status: "active", domain: "euv_lithography" } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "goal-737max-certification", label: "Obtain FAA type certificate for 737 MAX", layer: "goal", type: "goal",
          data: { priority: 0.90, status: "active", domain: "aviation_safety" } },
        { id: "goal-zero-hull-loss", label: "Zero hull loss rate during program", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "failed", domain: "aviation_safety" } },
        { id: "constraint-pilot-training-cost", label: "No new simulator training requirement", layer: "goal", type: "Constraint",
          data: { constraint_type: "soft", domain: "aviation_safety" } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "goal-15c-limit", label: "Limit warming to 1.5°C above preindustrial", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "at_risk", domain: "climate_policy" } },
        { id: "goal-net-zero-2050", label: "Net zero greenhouse gas emissions by 2050", layer: "goal", type: "goal",
          data: { priority: 0.95, status: "active", domain: "climate_policy" } },
        { id: "constraint-just-transition", label: "Coal phase-out must not harm energy-poor nations", layer: "goal", type: "Constraint",
          data: { constraint_type: "deontic", domain: "climate_policy" } },
        // ── Pandemic ──────────────────────────────────────────────────────────
        { id: "goal-pandemic-containment", label: "Contain COVID-19 spread within 14-day window", layer: "goal", type: "goal",
          data: { priority: 1.0, status: "failed", domain: "pandemic_governance" } },
        { id: "goal-who-ihr-reform", label: "Reform WHO IHR for faster PHEIC declaration", layer: "goal", type: "goal",
          data: { priority: 0.85, status: "active", domain: "pandemic_governance" } },
        // ── Surgical Robotics ──────────────────────────────────────────────────
        { id: "goal-robotic-safety-parity", label: "Robotic complication rate ≤ open surgery", layer: "goal", type: "goal",
          data: { priority: 0.92, status: "active", domain: "surgical_robotics" } },
      ],
      edges: [
        { source: "goal-reduce-tumor-burden", target: "constraint-cns-safety-gate", relation: "CONSTRAINED_BY" },
        { source: "goal-patient-safety", target: "goal-reduce-tumor-burden", relation: "CONSTRAINS" },
        { source: "goal-nuclear-safety", target: "constraint-uncertainty-gate", relation: "CONSTRAINED_BY" },
        { source: "goal-737max-certification", target: "constraint-pilot-training-cost", relation: "CONSTRAINED_BY" },
        { source: "goal-zero-hull-loss", target: "goal-737max-certification", relation: "REQUIRES" },
        { source: "goal-15c-limit", target: "goal-net-zero-2050", relation: "REQUIRES" },
        { source: "goal-net-zero-2050", target: "constraint-just-transition", relation: "CONSTRAINED_BY" },
      ],
    },

    governance: {
      nodes: [
        // ── Drug Discovery ─────────────────────────────────────────────────────
        { id: "prov-ev-bbb-assay", label: "Provenance: BBB assay validated", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-chemist-01", action: "validated", timestamp: "2024-07-10T09:15:00Z", domain: "drug_discovery" } },
        { id: "prov-dec-trial-approval", label: "Provenance: Trial approval decision record", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-oncologist-01", action: "created", timestamp: "2024-07-15T14:30:00Z", domain: "drug_discovery" } },
        { id: "dissent-molscreen-bbb", label: "Dissent: MolScreen-v2 vs. CNS deferral", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-ai-screen-01", disagreement_type: "conclusion", resolution_status: "overruled", domain: "drug_discovery" } },
        // ── Fukushima ──────────────────────────────────────────────────────────
        { id: "dissent-tepco-civil", label: "Dissent: TEPCO engineers vs. seawall deferral", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-tepco-civil", disagreement_type: "evidence_weight", resolution_status: "overruled_erased", domain: "fukushima_governance" } },
        { id: "prov-seawall-decision", label: "Provenance: Seawall deferral (provenance absent)", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-tepco-mgmt", action: "overruled_without_record", timestamp: "2008-06-01T00:00:00Z", domain: "fukushima_governance" } },
        { id: "perm-hirai-overrule", label: "Hirai authority override — canonical evidence set", layer: "governance", type: "Permission",
          data: { actor_id: "agent-hirai", access_type: "override_canonical", domain: "fukushima_governance" } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "dissent-pierson-737max", label: "Dissent: Ed Pierson vs. 737 MAX delivery (June 2019)", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-pierson-ed", disagreement_type: "process_safety", resolution_status: "overruled_reclassified", domain: "aviation_safety" } },
        { id: "dissent-boisjoly-challenger", label: "Dissent: Boisjoly vs. Challenger launch", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-boisjoly-roger", disagreement_type: "evidence_weight", resolution_status: "overruled", domain: "aviation_safety" } },
        { id: "prov-mcas-certification", label: "Provenance: FAA ODA MCAS certification record", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-faa-oda", action: "certified_delegated", timestamp: "2017-03-08T00:00:00Z", domain: "aviation_safety" } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "dissent-hayhoe-cop26", label: "Dissent: Katharine Hayhoe vs. Glasgow coal language", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-hayhoe", disagreement_type: "policy_adequacy", resolution_status: "overruled", domain: "climate_policy" } },
        { id: "prov-ipcc-ar6-adoption", label: "Provenance: IPCC AR6 SPM adoption (195 govts)", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-ipcc-wg1", action: "adopted", timestamp: "2021-08-09T00:00:00Z", domain: "climate_policy" } },
        // ── Pandemic ──────────────────────────────────────────────────────────
        { id: "dissent-tedros-pheic-delay", label: "Dissent: WHO emergency committee vs. PHEIC delay", layer: "governance", type: "DissentRecord",
          data: { actor_id: "agent-who-emergency-committee", disagreement_type: "timing", resolution_status: "delayed_14_days", domain: "pandemic_governance" } },
        { id: "prov-who-aerosol-update", label: "Provenance: WHO aerosol guidance update record", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-who-technical", action: "acknowledged_late", timestamp: "2020-07-09T00:00:00Z", domain: "pandemic_governance" } },
        // ── EUV ───────────────────────────────────────────────────────────────
        { id: "prov-cymer-acquisition", label: "Provenance: ASML–Cymer acquisition record", layer: "governance", type: "ProvenanceRecord",
          data: { actor_id: "agent-asml-systems", action: "acquired", timestamp: "2012-05-15T00:00:00Z", domain: "euv_lithography" } },
      ],
      edges: [
        { source: "dissent-tepco-civil", target: "dec-seawall-deferral-2008", relation: "CHALLENGES" },
        { source: "dissent-molscreen-bbb", target: "dec-trial-approval-2024", relation: "CHALLENGES" },
        { source: "dissent-pierson-737max", target: "dec-pierson-grounding-request", relation: "CHALLENGES" },
        { source: "dissent-boisjoly-challenger", target: "dec-challenger-launch-proceed", relation: "CHALLENGES" },
        { source: "dissent-hayhoe-cop26", target: "dec-glasgow-coal-phaseout", relation: "CHALLENGES" },
        { source: "dissent-tedros-pheic-delay", target: "dec-who-pheic-jan30", relation: "CHALLENGES" },
        { source: "prov-seawall-decision", target: "dec-seawall-deferral-2008", relation: "DOCUMENTS" },
        { source: "prov-mcas-certification", target: "dec-mcas-single-sensor", relation: "DOCUMENTS" },
        { source: "prov-cymer-acquisition", target: "dec-cymer-acquisition-2012", relation: "DOCUMENTS" },
      ],
    },

    agents: {
      nodes: [
        // ── Drug Discovery ─────────────────────────────────────────────────────
        { id: "agent-oncologist-01", label: "Dr. Sarah Chen", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "drug_discovery", competences: ["oncology","clinical trial design","RAS pathway"], calibration_score: 0.84 } },
        { id: "agent-chemist-01", label: "Dr. Marcus Webb", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "drug_discovery", competences: ["medicinal chemistry","covalent inhibitors","KRAS"], calibration_score: 0.79 } },
        { id: "agent-ai-screen-01", label: "MolScreen-v2", layer: "agents", type: "agents",
          data: { agent_type: "ai", domain: "drug_discovery", competences: ["virtual screening","docking","ADMET prediction"], calibration_score: 0.71 } },
        { id: "agent-statistician-01", label: "Dr. Ayaan Mirza (Biostatistics)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "drug_discovery", competences: ["trial design","adaptive enrichment","Bayesian"], calibration_score: 0.82 } },
        // ── Fukushima ──────────────────────────────────────────────────────────
        { id: "agent-tepco-mgmt", label: "TEPCO Corporate Management", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "fukushima_governance", calibration_score: 0.31 } },
        { id: "agent-tepco-civil", label: "TEPCO Civil Engineering Division", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "fukushima_governance", competences: ["coastal engineering","tsunami risk"], calibration_score: 0.76 } },
        { id: "agent-hirai", label: "Yanosuke Hirai (Tohoku Electric)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "fukushima_governance", competences: ["coastal engineering","seawall design","tacit judgment"], calibration_score: 0.94 } },
        { id: "agent-nisa", label: "NISA Nuclear Regulatory Body", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "fukushima_governance", calibration_score: 0.44 } },
        // ── EUV ───────────────────────────────────────────────────────────────
        { id: "agent-asml-systems", label: "ASML Systems Engineering", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "euv_lithography", competences: ["EUV integration","optics"], calibration_score: 0.82 } },
        { id: "agent-zeiss-optics", label: "Carl Zeiss SMT", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "euv_lithography", competences: ["EUV optics","Mo/Si mirror"], calibration_score: 0.88 } },
        { id: "agent-asml-technician", label: "Senior EUV Calibration Technician", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "euv_lithography", competences: ["droplet calibration","tacit process control"], calibration_score: 0.91 } },
        // ── Aviation Safety ────────────────────────────────────────────────────
        { id: "agent-pierson-ed", label: "Ed Pierson (Boeing Factory Manager)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "aviation_safety", competences: ["aircraft production","safety culture","military aviation"], calibration_score: 0.91 } },
        { id: "agent-boisjoly-roger", label: "Roger Boisjoly (Thiokol Engineer)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "aviation_safety", competences: ["structural engineering","O-ring seals","failure mode"], calibration_score: 0.89 } },
        { id: "agent-faa-oda", label: "FAA ODA (Delegated Authority)", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "aviation_safety", calibration_score: 0.52 } },
        { id: "agent-boeing-mgmt", label: "Boeing Program Management", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "aviation_safety", calibration_score: 0.38 } },
        // ── Climate Policy ─────────────────────────────────────────────────────
        { id: "agent-ipcc-wg1", label: "IPCC Working Group I", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "climate_policy", competences: ["climate modeling","attribution science"], calibration_score: 0.91 } },
        { id: "agent-hayhoe", label: "Katharine Hayhoe (Climate Scientist)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "climate_policy", competences: ["climate communication","policy translation"], calibration_score: 0.86 } },
        { id: "agent-cop26-presidency", label: "COP26 Presidency (UK)", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "climate_policy", calibration_score: 0.52 } },
        // ── Pandemic ──────────────────────────────────────────────────────────
        { id: "agent-who-technical", label: "WHO Technical Advisory Groups", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "pandemic_governance", competences: ["epidemiology","IHR","PHEIC"], calibration_score: 0.74 } },
        { id: "agent-who-emergency-committee", label: "WHO IHR Emergency Committee", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "pandemic_governance", calibration_score: 0.71 } },
        // ── Surgical Robotics ──────────────────────────────────────────────────
        { id: "agent-intuitive-surgical", label: "Intuitive Surgical (Manufacturer)", layer: "agents", type: "agents",
          data: { agent_type: "institution", domain: "surgical_robotics", competences: ["robotic surgery","device design","training"], calibration_score: 0.77 } },
        { id: "agent-trauma-surgeon-01", label: "Dr. Priya Nakamura (Trauma Surgeon)", layer: "agents", type: "agents",
          data: { agent_type: "human", domain: "surgical_robotics", competences: ["robotic surgery","haptic feedback","laparoscopy"], calibration_score: 0.88 } },
      ],
      edges: [
        { source: "agent-tepco-civil", target: "agent-tepco-mgmt", relation: "REPORTS_TO" },
        { source: "agent-tepco-mgmt", target: "dissent-tepco-civil", relation: "OVERRULED" },
        { source: "agent-pierson-ed", target: "dissent-pierson-737max", relation: "AUTHORED" },
        { source: "agent-boeing-mgmt", target: "agent-pierson-ed", relation: "OVERRULED" },
        { source: "agent-boisjoly-roger", target: "dissent-boisjoly-challenger", relation: "AUTHORED" },
        { source: "agent-hayhoe", target: "dissent-hayhoe-cop26", relation: "AUTHORED" },
        { source: "agent-cop26-presidency", target: "agent-hayhoe", relation: "OVERRULED" },
        { source: "agent-faa-oda", target: "agent-boeing-mgmt", relation: "DELEGATED_TO" },
        { source: "agent-asml-technician", target: "agent-asml-systems", relation: "WORKS_FOR" },
        { source: "agent-zeiss-optics", target: "agent-asml-systems", relation: "PARTNERS_WITH" },
        { source: "agent-oncologist-01", target: "agent-statistician-01", relation: "COLLABORATES_WITH" },
        { source: "agent-ipcc-wg1", target: "agent-cop26-presidency", relation: "ADVISES" },
        { source: "agent-who-emergency-committee", target: "agent-who-technical", relation: "INCLUDES" },
      ],
    },
  },

  summary: {
    total_nodes: 249,
    total_edges: 72,
    domain: "all",
    layer_filter: null,
  },
};
