import type { GraphOverview } from "./client";

export const DEMO_OVERVIEW: GraphOverview = {
  layers: {
    evidence: {
      nodes: [
        { id: "ev-kras-structure-2019", label: "Covalent targeting of KRAS G12C (AMG 510)", layer: "evidence", type: "evidence",
          data: { id: "ev-kras-structure-2019", source_type: "document", domain: "drug_discovery",
                  content_ref: "doi:10.1038/s41586-019-1694-1", tags: ["kras","sotorasib","structure"] } },
        { id: "ev-codebreak100-trial", label: "CodeBreaK 100 Phase II — Sotorasib NSCLC", layer: "evidence", type: "evidence",
          data: { id: "ev-codebreak100-trial", source_type: "document", domain: "drug_discovery",
                  content_ref: "doi:10.1056/NEJMoa2103695", tags: ["clinical-trial","sotorasib","NSCLC"] } },
        { id: "ev-bbb-assay-results", label: "BBB permeability assay — AMG510 analogues", layer: "evidence", type: "evidence",
          data: { id: "ev-bbb-assay-results", source_type: "sensor_window", domain: "drug_discovery",
                  uncertainty: 0.6, tags: ["bbb","permeability","assay"] } },
        { id: "ev-tepco-2008-assessment", label: "TEPCO internal tsunami risk assessment 2008", layer: "evidence", type: "evidence",
          data: { id: "ev-tepco-2008-assessment", source_type: "document", domain: "fukushima_governance",
                  uncertainty: 0.38, tags: ["tsunami","tepco","2008","risk"] } },
        { id: "ev-jogan-geological-record", label: "Jogan earthquake 869AD geological deposit record", layer: "evidence", type: "evidence",
          data: { id: "ev-jogan-geological-record", source_type: "document", domain: "fukushima_governance",
                  uncertainty: 0.19, tags: ["jogan","tsunami","geology","869AD"] } },
        { id: "ev-prepulse-asml-2003", label: "ASML pre-pulse technique — tin droplet flattening", layer: "evidence", type: "evidence",
          data: { id: "ev-prepulse-asml-2003", source_type: "document", domain: "euv_lithography",
                  uncertainty: 0.14, tags: ["prepulse","euv","asml","droplet"] } },
        { id: "ev-mirror-contamination-field", label: "Collector mirror contamination field data", layer: "evidence", type: "evidence",
          data: { id: "ev-mirror-contamination-field", source_type: "sensor_window", domain: "euv_lithography",
                  uncertainty: 0.22, tags: ["mirror","contamination","euv","sn"] } },
      ],
      edges: [],
    },

    context: {
      nodes: [
        { id: "dec-trial-approval-2024", label: "Phase II CNS cohort expansion — deferred", layer: "context", type: "context",
          data: { id: "dec-trial-approval-2024", question: "Should the Phase II expansion cohort include CNS-metastatic NSCLC patients?",
                  outcome: "deferred", is_exception: true, domain: "drug_discovery" } },
        { id: "prec-cns-deferral-2022", label: "CNS deferral precedent — AMG-224 (2022)", layer: "context", type: "Precedent",
          data: { id: "prec-cns-deferral-2022", confidence: 0.82, invocation_count: 1, domain: "drug_discovery" } },
        { id: "dec-seawall-deferral-2008", label: "Seawall upgrade deferred — TEPCO 2008", layer: "context", type: "context",
          data: { id: "dec-seawall-deferral-2008", question: "Should Fukushima Daiichi seawall be upgraded given 15.7m tsunami estimate?",
                  outcome: "deferred", is_exception: false, domain: "fukushima_governance" } },
        { id: "dec-tin-over-xenon-2007", label: "Tin plasma selected over xenon — ASML 2007", layer: "context", type: "context",
          data: { id: "dec-tin-over-xenon-2007", question: "Should EUV light source use tin or xenon plasma?",
                  outcome: "approved", is_exception: false, domain: "euv_lithography" } },
        { id: "dec-cymer-acquisition-2012", label: "Cymer acquisition — ASML 2012 ($2.5B)", layer: "context", type: "context",
          data: { id: "dec-cymer-acquisition-2012", question: "Should ASML acquire Cymer to internalize EUV source knowledge?",
                  outcome: "approved", is_exception: true, domain: "euv_lithography" } },
      ],
      edges: [
        { source: "dec-trial-approval-2024", target: "ev-bbb-assay-results", relation: "JUSTIFIED_BY" },
        { source: "dec-trial-approval-2024", target: "ev-codebreak100-trial", relation: "JUSTIFIED_BY" },
        { source: "dec-seawall-deferral-2008", target: "ev-tepco-2008-assessment", relation: "JUSTIFIED_BY" },
        { source: "dec-tin-over-xenon-2007", target: "ev-prepulse-asml-2003", relation: "JUSTIFIED_BY" },
      ],
    },

    knowledge: {
      nodes: [
        { id: "ent-KRAS",   label: "KRAS",             layer: "knowledge", type: "knowledge",
          data: { id: "ent-KRAS",   entity_type: "protein",   domain: "drug_discovery", attributes: { gene: "KRAS", mutation: "G12C" } } },
        { id: "ent-RAF",    label: "RAF",              layer: "knowledge", type: "knowledge",
          data: { id: "ent-RAF",    entity_type: "protein",   domain: "drug_discovery" } },
        { id: "ent-MEK",    label: "MEK",              layer: "knowledge", type: "knowledge",
          data: { id: "ent-MEK",    entity_type: "protein",   domain: "drug_discovery" } },
        { id: "ent-ERK",    label: "ERK",              layer: "knowledge", type: "knowledge",
          data: { id: "ent-ERK",    entity_type: "protein",   domain: "drug_discovery" } },
        { id: "ent-AMG510", label: "Sotorasib (AMG510)", layer: "knowledge", type: "knowledge",
          data: { id: "ent-AMG510", entity_type: "compound",  domain: "drug_discovery",
                  attributes: { mechanism: "covalent KRAS G12C inhibitor", fda_approved: true } } },
        { id: "mech-KRAS-activates-RAF",   label: "KRAS activates RAF",   layer: "knowledge", type: "Mechanism",
          data: { id: "mech-KRAS-activates-RAF",   mechanism_type: "causal",    confidence: 0.97 } },
        { id: "mech-RAF-activates-MEK",    label: "RAF phosphorylates MEK", layer: "knowledge", type: "Mechanism",
          data: { id: "mech-RAF-activates-MEK",    mechanism_type: "causal",    confidence: 0.96 } },
        { id: "mech-MEK-activates-ERK",    label: "MEK activates ERK",    layer: "knowledge", type: "Mechanism",
          data: { id: "mech-MEK-activates-ERK",    mechanism_type: "causal",    confidence: 0.98 } },
        { id: "mech-AMG510-inhibits-KRAS", label: "AMG510 inhibits KRAS G12C", layer: "knowledge", type: "Mechanism",
          data: { id: "mech-AMG510-inhibits-KRAS", mechanism_type: "inhibitory", confidence: 0.94 } },
        { id: "ent-fukushima-plant", label: "Fukushima Daiichi Nuclear Plant", layer: "knowledge", type: "knowledge",
          data: { id: "ent-fukushima-plant", entity_type: "facility", domain: "fukushima_governance",
                  attributes: { operator: "TEPCO", reactors: 6, seawall_height_m: 5.7 } } },
        { id: "ent-seawall-upgrade", label: "Seawall upgrade (deferred)", layer: "knowledge", type: "knowledge",
          data: { id: "ent-seawall-upgrade", entity_type: "action", domain: "fukushima_governance",
                  attributes: { required_height_m: 15.7, status: "deferred" } } },
        { id: "ent-jogan-event", label: "Jogan earthquake 869 AD", layer: "knowledge", type: "knowledge",
          data: { id: "ent-jogan-event", entity_type: "historical_event", domain: "fukushima_governance",
                  attributes: { year: 869, deposit_reach_km: 3 } } },
        { id: "mech-tsunami-sbo", label: "Tsunami flooding → station blackout", layer: "knowledge", type: "Mechanism",
          data: { id: "mech-tsunami-sbo", mechanism_type: "causal", confidence: 0.95, domain: "fukushima_governance" } },
        { id: "ent-euv-photon", label: "EUV photon 13.5nm", layer: "knowledge", type: "knowledge",
          data: { id: "ent-euv-photon", entity_type: "physical_entity", domain: "euv_lithography",
                  attributes: { wavelength_nm: 13.5, source: "tin plasma" } } },
        { id: "ent-tin-source", label: "LPP tin plasma EUV source", layer: "knowledge", type: "knowledge",
          data: { id: "ent-tin-source", entity_type: "component", domain: "euv_lithography",
                  attributes: { droplets_per_sec: 50000, co2_laser_kw: 20 } } },
        { id: "mech-laser-plasma", label: "CO2 laser → tin plasma → 13.5nm photons", layer: "knowledge", type: "Mechanism",
          data: { id: "mech-laser-plasma", mechanism_type: "causal", confidence: 0.96, domain: "euv_lithography" } },
        { id: "mech-sn-contamination", label: "Tin contamination → mirror degradation", layer: "knowledge", type: "Mechanism",
          data: { id: "mech-sn-contamination", mechanism_type: "causal", confidence: 0.91, domain: "euv_lithography" } },
      ],
      edges: [
        { source: "ent-KRAS",   target: "mech-KRAS-activates-RAF",   relation: "HAS_MECHANISM" },
        { source: "mech-KRAS-activates-RAF",   target: "ent-RAF",    relation: "TARGETS" },
        { source: "ent-RAF",    target: "mech-RAF-activates-MEK",    relation: "HAS_MECHANISM" },
        { source: "mech-RAF-activates-MEK",    target: "ent-MEK",   relation: "TARGETS" },
        { source: "ent-MEK",    target: "mech-MEK-activates-ERK",    relation: "HAS_MECHANISM" },
        { source: "mech-MEK-activates-ERK",    target: "ent-ERK",   relation: "TARGETS" },
        { source: "ent-AMG510", target: "mech-AMG510-inhibits-KRAS", relation: "HAS_MECHANISM" },
        { source: "mech-AMG510-inhibits-KRAS", target: "ent-KRAS",  relation: "TARGETS" },
        { source: "ent-fukushima-plant", target: "mech-tsunami-sbo", relation: "HAS_MECHANISM" },
        { source: "ent-tin-source", target: "mech-laser-plasma", relation: "HAS_MECHANISM" },
        { source: "mech-laser-plasma", target: "ent-euv-photon", relation: "PRODUCES" },
        { source: "ent-tin-source", target: "mech-sn-contamination", relation: "HAS_MECHANISM" },
      ],
    },

    goal: {
      nodes: [
        { id: "goal-reduce-tumor-burden", label: "Reduce KRAS G12C tumour burden", layer: "goal", type: "goal",
          data: { id: "goal-reduce-tumor-burden", priority: 0.95, status: "active", metric: "objective_response_rate", metric_target: 0.40, domain: "drug_discovery" } },
        { id: "goal-patient-safety", label: "Maintain acceptable safety profile", layer: "goal", type: "goal",
          data: { id: "goal-patient-safety", priority: 1.0, status: "active", metric: "grade3_adverse_events", metric_target: 0.15, domain: "drug_discovery" } },
        { id: "constraint-cns-safety-gate", label: "CNS expansion requires BBB uncertainty <0.4", layer: "goal", type: "Constraint",
          data: { id: "constraint-cns-safety-gate", constraint_type: "hard", domain: "drug_discovery" } },
        { id: "goal-nuclear-safety", label: "Prevent core damage at Fukushima Daiichi", layer: "goal", type: "goal",
          data: { id: "goal-nuclear-safety", priority: 1.0, status: "failed", domain: "fukushima_governance" } },
        { id: "constraint-uncertainty-gate", label: "Risk deferral requires uncertainty <0.4", layer: "goal", type: "Constraint",
          data: { id: "constraint-uncertainty-gate", constraint_type: "hard", domain: "fukushima_governance" } },
        { id: "goal-euv-throughput", label: "Achieve >100 wafers/hour EUV throughput", layer: "goal", type: "goal",
          data: { id: "goal-euv-throughput", priority: 0.9, status: "active", domain: "euv_lithography" } },
        { id: "goal-mirror-lifetime", label: "Extend collector mirror lifetime >1 year", layer: "goal", type: "goal",
          data: { id: "goal-mirror-lifetime", priority: 0.85, status: "active", domain: "euv_lithography" } },
      ],
      edges: [],
    },

    governance: {
      nodes: [
        { id: "prov-ev-bbb-assay", label: "Provenance: BBB assay validated", layer: "governance", type: "ProvenanceRecord",
          data: { id: "prov-ev-bbb-assay", actor_id: "agent-chemist-01", action: "validated",
                  timestamp: "2024-07-10T09:15:00Z", source_id: "ev-bbb-assay-results", domain: "drug_discovery" } },
        { id: "prov-dec-trial-approval", label: "Provenance: Trial approval decision", layer: "governance", type: "ProvenanceRecord",
          data: { id: "prov-dec-trial-approval", actor_id: "agent-oncologist-01", action: "created",
                  timestamp: "2024-07-15T14:30:00Z", source_id: "dec-trial-approval-2024", domain: "drug_discovery" } },
        { id: "dissent-tepco-civil", label: "Dissent: TEPCO engineers vs. seawall deferral", layer: "governance", type: "DissentRecord",
          data: { id: "dissent-tepco-civil", actor_id: "agent-tepco-civil", target_id: "dec-seawall-deferral-2008",
                  disagreement_type: "evidence_weight", resolution_status: "overruled", domain: "fukushima_governance" } },
        { id: "dissent-molscreen-bbb", label: "Dissent: MolScreen-v2 vs. CNS deferral", layer: "governance", type: "DissentRecord",
          data: { id: "dissent-molscreen-bbb", actor_id: "agent-ai-screen-01", target_id: "dec-trial-approval-2024",
                  disagreement_type: "conclusion", resolution_status: "overruled", domain: "drug_discovery" } },
      ],
      edges: [],
    },

    agents: {
      nodes: [
        { id: "agent-oncologist-01", label: "Dr. Sarah Chen", layer: "agents", type: "agents",
          data: { id: "agent-oncologist-01", agent_type: "human", domain: "drug_discovery",
                  competences: ["oncology","clinical trial design","RAS pathway"], calibration_score: 0.84 } },
        { id: "agent-chemist-01", label: "Dr. Marcus Webb", layer: "agents", type: "agents",
          data: { id: "agent-chemist-01", agent_type: "human", domain: "drug_discovery",
                  competences: ["medicinal chemistry","covalent inhibitors","KRAS"], calibration_score: 0.79 } },
        { id: "agent-ai-screen-01", label: "MolScreen-v2", layer: "agents", type: "agents",
          data: { id: "agent-ai-screen-01", agent_type: "ai", domain: "drug_discovery",
                  competences: ["virtual screening","docking","ADMET prediction"], calibration_score: 0.71 } },
        { id: "agent-tepco-mgmt", label: "TEPCO Corporate Management", layer: "agents", type: "agents",
          data: { id: "agent-tepco-mgmt", agent_type: "institution", domain: "fukushima_governance",
                  competences: ["corporate governance","regulatory relations"], calibration_score: 0.31 } },
        { id: "agent-tepco-civil", label: "TEPCO Civil Engineering Division", layer: "agents", type: "agents",
          data: { id: "agent-tepco-civil", agent_type: "institution", domain: "fukushima_governance",
                  competences: ["coastal engineering","tsunami risk","seawall design"], calibration_score: 0.76 } },
        { id: "agent-asml-systems", label: "ASML Systems Engineering", layer: "agents", type: "agents",
          data: { id: "agent-asml-systems", agent_type: "institution", domain: "euv_lithography",
                  competences: ["EUV integration","optics","overlay metrology"], calibration_score: 0.82 } },
        { id: "agent-zeiss-optics", label: "Carl Zeiss SMT", layer: "agents", type: "agents",
          data: { id: "agent-zeiss-optics", agent_type: "institution", domain: "euv_lithography",
                  competences: ["EUV optics","Mo/Si mirror fabrication","surface coating"], calibration_score: 0.88 } },
      ],
      edges: [],
    },
  },

  summary: {
    total_nodes: 47,
    total_edges: 18,
    domain: "all",
    layer_filter: null,
  },
};
